# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

host: :development


# development:
#   adapter: postgresql
#   encoding: unicode
#   database: morgans_development
#   pool: 5
#   host: localhost

development:
  adapter: postgresql
  encoding: unicode
  database: sparc_development
  pool: 5
  host: 54.164.65.141
  port: 5432
  username: postgres
  password: hipsters

test:
  adapter: postgresql
  encoding: unicode
  database: sparc_test
  pool: 5
  host: localhost

production:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: sparc_production
  pool: 10

